FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=120 -r requirements.txt

COPY app/streamlit_app/ ./app/streamlit_app/
COPY ml/artifacts/ ./ml/artifacts/

EXPOSE 8501

ENV API_URL = "http://backend:8000/api/v1"

CMD ["streamlit", "run", "app/streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
